<a href="https://colab.research.google.com/github/samwit/Beginners-Day/blob/master/JSv5/JS05_04_MNIST_CNN_Building_a_Basic_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Testing for GPU

To Test if you have GPU set up

Run the Cell below

if no GPU is found press Runtime (in the menu at the top) and choose "Change Runtime Type" to GPU
 

In [0]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [0]:
!ls

diagram12.gif  diagram4f.png  diagram6d.png  sample_data  sutils.py
diagram3c.gif  diagram5g.png  notebook1.zip  solutions


In [0]:
%matplotlib inline
import os, json
from glob import glob

import tensorflow as tf

import tensorflow.keras

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, Flatten,Input
from tensorflow.keras.layers import Conv2D, MaxPooling2D


In [0]:
batch_size = 128
num_classes = 10
epochs = 10
learning_rate = 0.001

# input image dimensions
img_rows, img_cols = 28, 28

In [0]:
# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [0]:

x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

In [0]:
input_shape

(28, 28, 1)

In [0]:
x_test.shape

(10000, 28, 28, 1)

In [0]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [0]:
# convert class vectors to binary class matrices
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)

In [0]:
Inp=Input(shape=input_shape)
x = Conv2D(32, kernel_size=(3, 3), activation='relu',name = 'Conv_01')(Inp)
x = MaxPooling2D(pool_size=(2, 2),name = 'MaxPool_01')(x)
x = Conv2D(64, (3, 3), activation='relu',name = 'Conv_02')(x)
x = MaxPooling2D(pool_size=(2, 2),name = 'MaxPool_02')(x)
x = Conv2D(64, (3, 3), activation='relu',name = 'Conv_03')(x)
x = Flatten(name = 'Flatten_01')(x)
x = Dense(64, activation='relu',name = 'Dense_01')(x)
x = Dropout(0.5,name = 'Dropout_02')(x)
output = Dense(num_classes, activation='softmax',name = 'Dense_02')(x)

In [0]:
model = Model(Inp,output)

## Calculating the number of parameters for Convolution Networks

Formula is (filters x (kernel_height x kernel_width) x inputs) 1 x filters = parameters

Conv_01 = 32 Filters , 3x3 Kernel = (32 x (3x3) x 1 input) + 1bias x filters = 320 parameters  
Conv_02 = 64 Filters , 3x3 Kernel = (64 x (3x3) x 32 inputs) + 1bias x filters = 18496 parameters 

Conv_03 = 64 Filters , 3x3 Kernel = (64 x (3x3) x 64 inputs) + 1bias x filters = 36928 parameters 

Dense_1 = (576 inputs * 64 units)+ 64 bias = 36928 
Dense_2 = (64 inputs * 10 units) +10 bias = 650


In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 28, 28, 1)         0         
_________________________________________________________________
Conv_01 (Conv2D)             (None, 26, 26, 32)        320       
_________________________________________________________________
MaxPool_01 (MaxPooling2D)    (None, 13, 13, 32)        0         
_________________________________________________________________
Conv_02 (Conv2D)             (None, 11, 11, 64)        18496     
_________________________________________________________________
MaxPool_02 (MaxPooling2D)    (None, 5, 5, 64)          0         
_________________________________________________________________
Conv_03 (Conv2D)             (None, 3, 3, 64)          36928     
_________________________________________________________________
Flatten_01 (Flatten)         (None, 576)               0         
__________

In [0]:
#optimizer
opt = tf.keras.optimizers.Adam(lr = learning_rate)

model.compile(loss=tf.keras.losses.categorical_crossentropy,
              optimizer= opt,
              metrics=['accuracy'])

In [0]:
hist = model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          callbacks = None,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 8s 132us/step - loss: 0.4107 - acc: 0.8701 - val_loss: 0.0634 - val_acc: 0.9803
Epoch 2/10
60000/60000 [==============================] - 6s 104us/step - loss: 0.1234 - acc: 0.9653 - val_loss: 0.0524 - val_acc: 0.9822
Epoch 3/10
60000/60000 [==============================] - 6s 105us/step - loss: 0.0849 - acc: 0.9756 - val_loss: 0.0443 - val_acc: 0.9855
Epoch 4/10
60000/60000 [==============================] - 6s 103us/step - loss: 0.0697 - acc: 0.9795 - val_loss: 0.0295 - val_acc: 0.9902
Epoch 5/10
60000/60000 [==============================] - 6s 105us/step - loss: 0.0600 - acc: 0.9825 - val_loss: 0.0319 - val_acc: 0.9896
Epoch 6/10
60000/60000 [==============================] - 6s 104us/step - loss: 0.0499 - acc: 0.9850 - val_loss: 0.0357 - val_acc: 0.9897
Epoch 7/10
60000/60000 [==============================] - 6s 105us/step - loss: 0.0464 - acc: 0.9865 - val_loss: 0.0264 - 

In [0]:
# plot_train(hist)

In [0]:
model.save_weights('basic_cnn.h5')

In [0]:
model.save('./test_dir/mnist_cnn_model.h5')

In [0]:
!ls test_dir

mnist_cnn_model.h5


In [0]:
!mkdir test_dir

In [0]:
!ls

basic_cnn.h5  gdrive.py		  sample_data  test_dir
data	      mnist_cnn_model.h5  sutils.py


In [0]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
!ls

basic_cnn.h5  data  gdrive.py  mnist_cnn_model.h5  sample_data	sutils.py


In [0]:
# gdrive.upload_file('basic_cnn.h5', 'application/h5')

In [0]:
# gdrive.upload_file('mnist_cnn_model.h5', 'application/h5')

In [0]:
Inp=Input(shape=input_shape)
x = Conv2D(32, kernel_size=(3, 3), activation='relu',name = 'Conv_01')(Inp)
x = Conv2D(64, (3, 3), activation='relu',name = 'Conv_02')(x)
x = MaxPooling2D(pool_size=(2, 2),name = 'MaxPool_01')(x)
x = Conv2D(128, (3, 3), activation='relu',name = 'Conv_03')(x)
x = Conv2D(256, (3, 3), activation='relu',name = 'Conv_04')(x)
x = MaxPooling2D(pool_size=(2, 2),name = 'MaxPool_02')(x)
x = Dropout(0.25,name = 'Dropout_01')(x)
x = Flatten(name = 'Flatten_01')(x)
x = Dense(128, activation='relu',name = 'Dense_01')(x)
x = Dropout(0.5,name = 'Dropout_02')(x)
output = Dense(num_classes, activation='softmax',name = 'Dense_02')(x)

In [0]:
model = Model(Inp,output)

## Calculating the number of parameters for Convolution Networks

Formula is (filters x (kernel_height x kernel_width) x inputs) 1 x filters = parameters

Conv_01 = 32 Filters , 3x3 Kernel = (32 x (3x3) x 1 input) + 1bias x filters = 320 parameters  
Conv_02 = 64 Filters , 3x3 Kernel = (64 x (3x3) x 32 inputs) + 1bias x filters = 18496 parameters   
Conv_03 = 128 Filters , 3x3 Kernel = (128 x (3x3) x 64 input) + 1bias x filters = 73856 parameters    
Conv_04 = 256 Filters , 3x3 Kernel = (256 x (3x3) x 128 inputs) + 1bias x filters = 295168 parameters 

Dense_1 = (4096 inputs * 128 units)+ 128 bias = 524,416  
Dense_2 = (128 inputs * 10 units) +10 bias = 1290

In [0]:
model.summary()